export type AboutMeRow = {
    id: number,
    title: string,
    description: string,
    focus_label: string | null,
    focus_value: string | null,
    stack_label: string | null,
    stack_value: string | null,
    features: string[],
    btn_text1: string | null,
    btn_href1: string | null,
    btn_text2: string | null,
    btn_href2: string | null,
    image: string | null,
    created_at: Date,
    updated_at: Date,
}

export type AboutMeEntity = {
    id: number,
    title: string,
    description: string,
    focusLabel: string | null,
    focusValue: string | null,
    stackLabel: string | null,
    stackValue: string | null,
    features: string[],
    btnText1: string | null,
    btnHref1: string | null,
    btnText2: string | null,
    btnHref2: string | null,
    image: string | null,
    createdAt: Date,
    updatedAt: Date,
}

export type AboutMeInsert = {
    title: string,
    description: string,
    focusLabel?: string | null,
    focusValue?: string | null,
    stackLabel?: string | null,
    stackValue?: string | null,
    features?: string[],
    btnText1?: string | null,
    btnHref1?: string | null,
    btnText2?: string | null,
    btnHref2?: string | null,
    image?: string | null,
}

export type AboutMeUpdate = Partial<{
    title: string,
    description: string,
    focusLabel: string | null,
    focusValue: string | null,
    stackLabel: string | null,
    stackValue: string | null,
    features: string[],
    btnText1: string | null,
    btnHref1: string | null,
    btnText2: string | null,
    btnHref2: string | null,
    image: string | null,
}>